dist: focal

language: php

php:
  - 7.4

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - nvm use 12.7.0
  - npm i -g npm@6.14.9
  - node -v
  - npm install
  - npm run dev
  - php artisan key:generate

cache:
  directories:
    - vendor
    - node_modules
